"""
Vectora Universal Trace ID — open standard.

Format:  vct_{unix_timestamp_ms}_{random_8hex}
Example: vct_1749648123456_a3f7b2c1

Properties:
- Prefix `vct_` identifies the trace as Vectora-issued in any log or report
- Millisecond Unix timestamp makes IDs time-sortable and collision-free across orgs
- 8-character hex suffix adds additional collision resistance
- Total length ~28 characters — short enough for UI display, long enough to be unique
- Cross-pillar: the same trace_id column appears in predictions, decision_log,
  explanations, llm_calls, agent_runs, and incident tables
- Generated by vectora-sdk at prediction time, passed to the platform via the ingest API

This format is an open standard. Any tool may generate or validate Vectora trace IDs
by importing this module.
"""

from __future__ import annotations

import re
import time
from secrets import token_hex

TRACE_ID_PATTERN: re.Pattern[str] = re.compile(
    r"^vct_\d{13}_[a-f0-9]{8}$",
    re.IGNORECASE,
)


def generate_trace_id() -> str:
    """Return a new Vectora Universal Trace ID.

    Format: vct_{unix_timestamp_ms}_{random_8hex}
    """
    ms = int(time.time() * 1000)
    suffix = token_hex(4)  # 4 bytes → 8 hex chars
    return f"vct_{ms}_{suffix}"


def is_valid_trace_id(value: str) -> bool:
    """Return True if *value* matches the Vectora Universal Trace ID format."""
    return bool(TRACE_ID_PATTERN.fullmatch(value))
